// Static JSON data files (pre-processed from CSV sources)
// Run `node data/export-archive-data.js` to regenerate from CSV files
export const DATA_CONFIG = {
    // Split data loading for optimized performance
    // Core data: lightweight records for card display (~8MB, loads first)
    archive_core: './data/archive-core.json',

    // Details: full summaries, quotes, concepts, tags (~11MB, loads on demand)
    archive_details: './data/archive-details.json',

    // Entities: for the entity browser and record connections (~1MB, loads on demand)
    archive_entities: './data/archive-entities.json',

    // Full data file (backward compatible, for fallback)
    archive_json: './data/archive-data.json',

    // Prebuilt analytics aggregates (~1KB): powers the default Analytics
    // dashboard view without loading SQLite. Regenerated by export-archive-data.js.
    archive_analytics: './data/archive-analytics.json',

    // Prebuilt MiniSearch full-text index (~1MB, article records only): loaded
    // lazily on first search to add body/author recall over the card-only
    // substring blob (#276). Regenerated by export-archive-data.js.
    search_index: './data/search-index.json',

    // Social-post body index: kept separate from the article index so both
    // remain lazy resources and browse-only visits download neither (#669).
    // Regenerated by export-archive-data.js.
    social_search_index: './data/social-search-index.json'
};

// Branded in-archive report form (#509). `endpoint` is the public Apps Script
// web-app /exec URL that files the GitHub issue on the reader's behalf (see
// automation/apps-script/Code.gs doPost). It is a public URL, not a secret.
// Left empty until the web app is deployed: while empty, the report modal
// degrades to the existing GitHub new-issue deep link, so nothing breaks before
// launch. Set this to the /exec URL to turn the branded submit on.
export const REPORT_CONFIG = {
    endpoint: 'https://script.google.com/macros/s/AKfycbylsBFcpmqT6WE6Hl_KNOQG61x83nYjBmDgtDwBbiyqdmN60_TFKJhabm9BhgwD1RgwdA/exec'
};

export const ITEMS_PER_PAGE = 24;

export const CONTENT_TYPE_OPTIONS = [
    { label: 'All', value: null },
    { label: 'Articles', value: 'article' },
    { label: 'Twitter/X', value: 'twitter' },
    { label: 'Bluesky', value: 'bluesky' },
];

export const COLORS = [
    { bg: '#e0f2fe', text: '#075985', border: '#bae6fd' }, // Sky
    { bg: '#f0fdf4', text: '#166534', border: '#bbf7d0' }, // Green
    { bg: '#fffbeb', text: '#92400e', border: '#fde68a' }, // Amber
    { bg: '#fdf2f8', text: '#9d174d', border: '#fbcfe8' }, // Pink
    { bg: '#f5f3ff', text: '#5b21b6', border: '#ddd6fe' }, // Violet
    { bg: '#fff7ed', text: '#9a3412', border: '#ffedd5' }  // Orange
];

// Shared entity type configuration (used by EntityBrowser, RecordModal)
export const ENTITY_TYPE_CONFIG = {
  Person: { color: '#075985', bg: '#e0f2fe', label: 'People' },
  Organization: { color: '#166534', bg: '#f0fdf4', label: 'Organizations' },
  Concept: { color: '#92400e', bg: '#fffbeb', label: 'Concepts' },
  Work: { color: '#9d174d', bg: '#fdf2f8', label: 'Works' },
  Event: { color: '#5b21b6', bg: '#f5f3ff', label: 'Events' },
  Location: { color: '#9a3412', bg: '#fff7ed', label: 'Locations' }
};

export { ERAS } from '../data/eras.js?v=3.8.32';

export const FEATURED_WORKS = [
  {
    id: 'feat-dissertation',
    title: 'The Impossible Press (1986)',
    description: 'Rosen\'s PhD dissertation exploring the decline of the "public" as a social group and the rise of the mass audience. It contrasts the democratic ideal of a "universal town meeting" with the realities of modern communication.',
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&q=80&w=800',
    link: 'https://pressthink.org/j/rosen-archive/dissertation/reader/',
    type: 'PhD Dissertation'
  },
  {
    id: 'feat-1',
    title: 'The View from Nowhere',
    description: 'A seminal critique of the claim to objectivity in journalism, arguing that the "view from nowhere" is a bid for trust that actually disconnects journalists from the public.',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&q=80&w=800',
    link: 'https://pressthink.org/2010/11/the-view-from-nowhere-questions-and-answers/',
    type: 'Key Concept'
  },
  {
    id: 'feat-2',
    title: 'What Are Journalists For?',
    description: 'Rosen\'s influential book exploring the Public Journalism movement of the 1990s, arguing for a press that helps communities solve their own problems.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800',
    link: 'https://yalebooks.yale.edu/book/9780300089073/what-are-journalists-for/',
    type: 'Book'
  },
  {
    id: 'feat-3',
    title: 'PressThink',
    description: 'The long-running blog where Rosen has chronicled the decline of the legacy press and the rise of the web.',
    image: 'https://images.unsplash.com/photo-1432821596592-e2c18b78144f?auto=format&fit=crop&q=80&w=800',
    link: 'https://pressthink.org/',
    type: 'Blog'
  },
  {
    id: 'feat-4',
    title: 'The Church of the Savvy',
    description: 'A critique of political journalism that focuses on strategy, optics, and "who\'s winning" rather than the substance of policy.',
    image: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&q=80&w=800',
    link: 'https://pressthink.org/2010/06/clowns-to-the-left-of-me-jokers-to-the-right-on-the-actual-ideology-of-the-american-press/',
    type: 'Key Concept'
  },
  {
    id: 'feat-5',
    title: 'Audience Atomization',
    description: 'The theory that the broadcast era treated the audience as disconnected individuals, which the internet disrupted.',
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=800',
    link: 'https://pressthink.org/2009/01/12/audience-atomization-overcome-why-the-internet-weakens-the-authority-of-the-press/',
    type: 'Key Concept'
  },
  {
    id: 'feat-6',
    title: 'Public Journalism: A Case for Public Scholarship (1995)',
    description: 'An early argument for academics to engage with practitioners and the public, not just other scholars. Rosen makes the case that journalism reform requires intellectual work done in the open.',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=800',
    link: 'https://berks.psu.edu/sites/berks/files/campus/rosen.pdf',
    type: 'Essay'
  },
  {
    id: 'feat-7',
    title: 'The Master Narrative in Journalism (2003)',
    description: 'An anatomy of the story the press tells about itself: that professional journalists are the heroes holding powerful people accountable. Rosen argues this self-image prevents journalists from seeing their own structural problems.',
    image: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&q=80&w=800',
    link: 'http://archive.pressthink.org/2003/09/08/basics_master.html',
    type: 'Blog Post'
  },
  {
    id: 'feat-8',
    title: 'The Press Is a Player (2004)',
    description: 'A challenge to the notion that the press merely observes. Rosen argues that journalism is an active participant in political events, not a neutral mirror reflecting them.',
    image: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&q=80&w=800',
    link: 'http://archive.pressthink.org/2004/01/23/press_player_p.html',
    type: 'Blog Post'
  },
  {
    id: 'feat-9',
    title: 'Bloggers vs. Journalists Is Over (2005)',
    description: 'An early declaration that the debate between traditional journalists and bloggers missed the point. The real shift was that the audience now had publishing tools, changing journalism permanently.',
    image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=800',
    link: 'http://archive.pressthink.org/2005/01/21/berk_essy_p.html',
    type: 'Blog Post'
  },
  {
    id: 'feat-10',
    title: 'The Production of Innocence (2005)',
    description: 'On how the press maintains its claim to neutrality by producing "innocence" — the appearance of having no stake in the outcome. Rosen traces this to the professional attitude he critiqued in the dissertation.',
    image: 'https://images.unsplash.com/photo-1521791055366-0d553872125f?auto=format&fit=crop&q=80&w=800',
    link: 'http://archive.pressthink.org/2005/07/02/sprm_crt_p.html',
    type: 'Blog Post'
  },
  {
    id: 'feat-11',
    title: 'The People Formerly Known as the Audience (2006)',
    description: 'One of Rosen\'s most widely read pieces. A manifesto written from the perspective of the audience, declaring that people once treated as passive consumers of news are now active participants.',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=800',
    link: 'http://archive.pressthink.org/2006/06/27/ppl_frmr_p.html',
    type: 'Blog Post'
  },
  {
    id: 'feat-12',
    title: 'What I Learned from Assignment Zero (2007)',
    description: 'A candid post-mortem on Assignment Zero, Rosen\'s experiment in "crowdsourced" journalism. The project partially failed, and Rosen explains why — a rare example of a public intellectual analyzing his own mistakes in real time.',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800',
    link: 'http://archive.pressthink.org/2007/10/09/what_i_learned_p.html',
    type: 'Blog Post'
  },
  {
    id: 'feat-13',
    title: 'The Beast Without a Brain (2008)',
    description: 'A critique of horse-race election coverage. Rosen argues that campaign journalism organized around who\'s winning and who\'s losing serves the needs of journalists, not citizens.',
    image: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&q=80&w=800',
    link: 'http://archive.pressthink.org/2008/01/20/the_campaign_pr_p.html',
    type: 'Blog Post'
  },
  {
    id: 'feat-14',
    title: 'The Quest for Innocence and the Loss of Reality (2010)',
    description: 'A deepening of the "production of innocence" argument. Rosen shows how the press\'s insistence on appearing neutral eventually costs it the ability to describe reality accurately.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
    link: 'http://archive.pressthink.org/2010/02/21/innocence_p.html',
    type: 'Blog Post'
  },
  {
    id: 'feat-15',
    title: 'The Citizens\' Agenda in Election Coverage (2011)',
    description: 'A proposal for election coverage that starts with what citizens want to know, not what campaigns want to talk about. Rosen and Amanda Michel outline a practical alternative to horse-race journalism.',
    image: 'https://images.unsplash.com/photo-1494172961521-33799ddd43a5?auto=format&fit=crop&q=80&w=800',
    link: 'https://www.theguardian.com/commentisfree/cifamerica/2011/dec/08/citizens-agenda-election-coverage',
    type: 'Essay'
  },
  {
    id: 'feat-16',
    title: 'Asymmetry Fries the Circuits (2016)',
    description: 'An argument that the American press is structurally unable to cover two political parties that are not equally committed to democratic norms. The assumption of symmetry becomes a form of distortion.',
    image: 'https://images.unsplash.com/photo-1551817958-d9d86fb29431?auto=format&fit=crop&q=80&w=800',
    link: 'https://pressthink.org/2016/09/asymmetry-between-the-major-parties-fries-the-circuits-of-the-mainstream-press/',
    type: 'Blog Post'
  },
  {
    id: 'feat-17',
    title: 'Winter Is Coming (2016)',
    description: 'Written shortly after the 2016 election, a warning about what Trump\'s presidency would mean for the press. Rosen argues that the normal rules of political journalism had been suspended and journalists needed to recognize that.',
    image: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?auto=format&fit=crop&q=80&w=800',
    link: 'https://pressthink.org/2016/12/winter-coming-prospects-american-press-trump/',
    type: 'Blog Post'
  },
  {
    id: 'feat-18',
    title: 'America\'s Press and the Asymmetric War for Truth (2020)',
    description: 'A major essay in the New York Review of Books synthesizing years of argument about political asymmetry, truth-telling, and the press\'s failure to adapt to a political environment designed to overwhelm it.',
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&q=80&w=800',
    link: 'https://www.nybooks.com/online/2020/11/01/americas-press-and-the-asymmetric-war-for-truth/',
    type: 'Essay'
  },
  {
    id: 'feat-19',
    title: 'Interview on the Ezra Klein Show (2021)',
    description: 'A long-form conversation where Rosen explains his core ideas to a wide audience: the view from nowhere, audience atomization, asymmetry, and the structural crisis in American journalism.',
    image: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&q=80&w=800',
    link: 'https://www.nytimes.com/2021/11/12/podcasts/transcript-ezra-klein-show-jay-rosen.html',
    type: 'Interview'
  },
  {
    id: 'feat-20',
    title: 'Trump, Truth, and "Freedom from Fact" (2025)',
    description: 'One of Rosen\'s most recent public talks, examining how the relationship between politics and truth has deteriorated further. The concept of "freedom from fact" describes a political movement that treats factual accountability as a constraint to be escaped.',
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&q=80&w=800',
    link: 'https://www.bylinesupplement.com/p/trump-truth-and-freedom-from-fact',
    type: 'Talk'
  }
];
